import { StyleSheet } from 'react-native';

import { C, W } from './theme';

/* ============================ ESTILOS ============================ */
export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.chileanNavy, alignItems: 'center' },
  frame: { flex: 1, width: '100%', maxWidth: 440, backgroundColor: C.chileanBg },

  rowCenter: { flexDirection: 'row', alignItems: 'center', gap: 6, minWidth: 0 },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', minWidth: 0 },
  rowWrap: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8, minWidth: 0 },

  /* Header */
  header: {
    backgroundColor: C.white,
    paddingHorizontal: 16,
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: C.slate100,
  },
  logoImg: { width: 130, height: 38 },
  /* Accesos del header: lo que salió de la barra inferior pero sigue en la app
     (Motor de Precios, y Subastas mientras Autored resuelve el punto 46). */
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: C.slate100,
    alignItems: 'center',
    justifyContent: 'center',
  },

  main: { flex: 1, backgroundColor: C.chileanBg },
  mainContent: { paddingTop: 16, paddingBottom: 24 },

  /* Nav */
  nav: {
    backgroundColor: C.white,
    borderTopWidth: 1,
    borderTopColor: C.slate200,
    paddingHorizontal: 8,
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  navBtn: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderRadius: 12,
    minWidth: 0,
  },
  /* Sin etiqueta el botón queda más alto para que el área de toque no se achique
     al sacarle la línea de texto. */
  navBtnIconOnly: { paddingVertical: 10 },
  navLabel: { fontSize: 10, fontWeight: W.bold, textAlign: 'center' },
  navBadge: {
    position: 'absolute',
    top: -6,
    right: -8,
    backgroundColor: C.teal500,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: C.white,
    paddingHorizontal: 2,
  },
  navBadgeText: { color: C.white, fontWeight: W.black, fontSize: 8 },
  stockFabWrap: {
    position: 'absolute',
    zIndex: 20,
    elevation: 7,
  },
  fab: {
    backgroundColor: C.chileanTeal,
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: C.white,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },

  /* Notificación */
  notif: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 50,
    backgroundColor: C.teal800,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: C.teal500,
    alignSelf: 'center',
    maxWidth: 440 - 32,
    width: '100%',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  notifText: { color: C.white, fontSize: 13, fontWeight: W.semibold, flex: 1 },

  /* Inicio */
  homeGreeting: { minWidth: 0 },
  h2: { fontSize: 22, fontWeight: W.bold, color: C.graphite },
  h2Black: { fontSize: 20, fontWeight: W.black, color: C.slate800, flexShrink: 1 },
  subMuted: { fontSize: 13, color: C.slate500, flexShrink: 1, marginTop: 2 },
  screenHead: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10, minWidth: 0 },
  screenHeadText: { flex: 1, minWidth: 0 },
  screenHeadAction: { flexShrink: 0, alignSelf: 'flex-start' },

  /* Motor de precios — botón único de acceso */
  motorBtn: {
    backgroundColor: C.brand,
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    shadowColor: C.brandDeep,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  motorBtnIcon: {
    width: 54,
    height: 54,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  motorBtnTitle: { color: C.white, fontSize: 19, fontWeight: W.bold, letterSpacing: -0.2 },
  motorBtnSub: { color: 'rgba(255,255,255,0.9)', fontSize: 13, marginTop: 3 },

  /* Motor de precios — pantalla */
  motorField: { gap: 6 },
  motorDemoRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap', marginTop: 2 },
  motorDemoLabel: { fontSize: 11, color: C.slate400, fontWeight: W.semibold },
  motorDemoChip: {
    backgroundColor: C.slate100,
    borderWidth: 1,
    borderColor: C.slate200,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  motorDemoChipText: { fontSize: 11, fontWeight: W.bold, color: C.slate600, letterSpacing: 0.5 },
  motorKmWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.slate200,
    borderRadius: 12,
    paddingRight: 14,
  },
  motorKmInput: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 18,
    fontWeight: W.bold,
    color: C.slate800,
  },
  motorKmSuffix: { fontSize: 13, fontWeight: W.bold, color: C.slate400 },
  motorKmHint: { fontSize: 11, color: C.slate500, fontWeight: W.medium },
  motorTasarBtn: {
    backgroundColor: C.chileanTeal,
    borderRadius: 14,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  motorTasarText: { color: C.white, fontSize: 15, fontWeight: W.black },

  motorCarBox: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.slate200,
    borderRadius: 16,
    padding: 14,
  },
  motorCarIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: C.teal50, alignItems: 'center', justifyContent: 'center' },
  motorCarTitle: { fontSize: 15, fontWeight: W.extrabold, color: C.slate800, flexShrink: 1 },
  motorCarSub: { fontSize: 11, color: C.slate500, marginTop: 1, flexShrink: 1 },
  motorConfTag: { backgroundColor: C.emerald100, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 9999 },
  motorConfText: { fontSize: 9, fontWeight: W.black, color: C.emerald800 },

  motorResultBox: {
    backgroundColor: C.teal900,
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    gap: 2,
  },
  motorResultLabel: { color: C.teal200, fontSize: 12, fontWeight: W.bold, textTransform: 'uppercase', letterSpacing: 0.5 },
  motorResultRange: { color: C.white, fontSize: 30, fontWeight: W.black },
  motorResultAnd: { color: C.teal300, fontSize: 12, fontWeight: W.bold },
  motorResultFoot: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, marginTop: 12 },
  motorResultFootText: { color: C.teal200, fontSize: 11, flex: 1, lineHeight: 15 },

  motorBreakdown: {
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.slate200,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  motorBreakTitle: {
    fontSize: 11,
    fontWeight: W.extrabold,
    color: C.slate400,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    paddingVertical: 10,
  },
  motorBreakRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: C.slate100,
  },
  motorBreakRowLast: { borderTopWidth: 1, borderTopColor: C.slate200 },
  motorBreakLabel: { fontSize: 12, color: C.slate600, fontWeight: W.medium, flex: 1 },
  motorBreakValue: { fontSize: 13, color: C.slate700, fontWeight: W.bold, flexShrink: 1, textAlign: 'right' },
  motorBreakValueStrong: { fontSize: 14, color: C.slate800, fontWeight: W.extrabold, flexShrink: 1, textAlign: 'right' },

  motorCompRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.slate100,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  motorCompTitle: { fontSize: 13, fontWeight: W.bold, color: C.slate700 },
  motorCompSub: { fontSize: 10, color: C.slate400, marginTop: 1 },
  motorCompPrice: { fontSize: 13, fontWeight: W.extrabold, color: C.slate800, flexShrink: 0 },

  motorTakeBtn: {
    backgroundColor: C.slate800,
    borderRadius: 14,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  motorTakeText: { color: C.white, fontSize: 14, fontWeight: W.bold },
  motorDisclaimer: { fontSize: 10, color: C.slate400, textAlign: 'center', lineHeight: 14 },

  // Mayúsculas con tracking amplio, igual que el wordmark "AUTORED" del logo.
  sectionLabel: { fontWeight: W.bold, fontSize: 11, color: C.slate400, textTransform: 'uppercase', letterSpacing: 1.4 },

  /* ---------- AutoSafe ---------- */
  // La barra cian es el único acento estructural: agrupa las dos tarjetas del socio.
  asBlock: { flexDirection: 'row', gap: 10 },
  asBrandBar: { width: 3, borderRadius: 9999, backgroundColor: C.chileanTeal },
  asCardHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, gap: 8, minWidth: 0 },
  asBrandLabel: {
    flex: 1,
    fontWeight: W.bold,
    fontSize: 10,
    color: C.slate400,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  asFolio: { fontSize: 10, fontWeight: W.extrabold, color: C.slate500, letterSpacing: 0.4 },

  asVerdictStrip: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  asVerdictCell: {
    flex: 1,
    minWidth: 86,
    alignItems: 'center',
    gap: 5,
    paddingVertical: 10,
    paddingHorizontal: 4,
    backgroundColor: C.slate50,
    borderWidth: 1,
    borderColor: C.slate100,
    borderRadius: 12,
    overflow: 'hidden',
  },
  asVerdictBar: { position: 'absolute', top: 0, left: 0, right: 0, height: 3 },
  asVerdictLabel: {
    fontSize: 9,
    fontWeight: W.bold,
    color: C.slate400,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginTop: 2,
  },
  asVerdictValue: { fontSize: 10, fontWeight: W.extrabold, textAlign: 'center', lineHeight: 13 },

  asAlertStrip: { borderLeftWidth: 3, borderRadius: 8, padding: 10, marginTop: 12, gap: 3 },
  asAlertTitle: { fontSize: 12, fontWeight: W.extrabold },
  asAlertText: { fontSize: 11, color: C.slate600, fontWeight: W.medium, lineHeight: 16 },

  asLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: C.slate100,
  },
  asLinkText: { fontSize: 13, fontWeight: W.extrabold, color: C.slate800, flexShrink: 1 },
  asMetaText: { fontSize: 10, color: C.slate400, fontWeight: W.medium, marginTop: 2, lineHeight: 15 },

  asClientBlock: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: C.slate100 },
  asClientTitle: {
    fontSize: 10,
    fontWeight: W.bold,
    color: C.slate400,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  asClientHint: { fontSize: 11, color: C.slate500, fontWeight: W.medium, lineHeight: 16, marginTop: 4 },

  // CTAs de AutoSafe en grafito: se leen como producto del socio, no como acción core de AutoRed.
  asCtaDark: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: C.slate800,
    borderRadius: 12,
    paddingVertical: 13,
    paddingHorizontal: 14,
    marginTop: 10,
    gap: 8,
  },
  asCtaDarkText: { color: C.white, fontWeight: W.extrabold, fontSize: 12 },
  asCtaPrice: { color: C.teal400, fontWeight: W.extrabold, fontSize: 12 },
  asCtaDisabled: { backgroundColor: C.slate100 },

  asPitchRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 7 },
  asPitchText: { flex: 1, fontSize: 11.5, color: C.slate600, fontWeight: W.medium, lineHeight: 17 },
  asQuoteRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 10,
    columnGap: 16,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: C.slate100,
  },

  asTimelineItem: { flexDirection: 'row', gap: 10 },
  asTimelineGutter: { alignItems: 'center', width: 14 },
  asTimelineNode: {
    width: 11,
    height: 11,
    borderRadius: 9999,
    borderWidth: 2,
    borderColor: C.slate300,
    backgroundColor: C.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 3,
  },
  asTimelineNodeDone: { backgroundColor: C.slate800, borderColor: C.slate800 },
  asTimelineNodeActive: { backgroundColor: C.chileanTeal, borderColor: C.chileanTeal },
  asTimelineLine: { flex: 1, width: 2, backgroundColor: C.slate200, marginVertical: 2 },
  asTimelineLabel: { flex: 1, minWidth: 0, fontSize: 12, fontWeight: W.bold, color: C.slate400, paddingRight: 8 },
  asTimelineDate: { fontSize: 10, fontWeight: W.bold, color: C.slate400, flexShrink: 0 },
  asTimelineDetail: { fontSize: 11, color: C.slate500, fontWeight: W.medium, lineHeight: 16, marginTop: 2 },

  asTransferMeta: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: C.slate100, gap: 8 },
  asMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
  asMetaRowLabel: { fontSize: 11, color: C.slate400, fontWeight: W.bold, width: 108 },
  asMetaRowValue: { flex: 1, minWidth: 0, fontSize: 11.5, color: C.slate600, fontWeight: W.semibold, textAlign: 'right' },

  asChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  asChip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: C.slate200,
    backgroundColor: C.slate50,
  },
  asChipActive: { backgroundColor: C.chileanNavy, borderColor: C.chileanNavy },
  asChipText: { fontSize: 12, fontWeight: W.bold, color: C.slate600 },

  asPartyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    backgroundColor: C.slate50,
    borderWidth: 1,
    borderColor: C.slate100,
    borderRadius: 12,
    padding: 12,
  },
  asPartyRol: { fontSize: 10, fontWeight: W.bold, color: C.slate400, textTransform: 'uppercase', letterSpacing: 0.5 },
  asPartyName: { fontSize: 13, fontWeight: W.extrabold, color: C.slate800, textAlign: 'right', flexShrink: 1 },
  asPartyPhone: { fontSize: 11, color: C.slate500, fontWeight: W.medium, flexShrink: 1 },

  asCostRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', paddingVertical: 8 },
  asCostLabel: { fontSize: 12, color: C.slate600, fontWeight: W.semibold },
  asCostNota: { fontSize: 10, color: C.slate400, fontWeight: W.medium, lineHeight: 14, marginTop: 2 },
  asCostValue: { fontSize: 12, color: C.slate700, fontWeight: W.bold },
  asCostTotalRow: { borderTopWidth: 1, borderTopColor: C.slate200, marginTop: 4, paddingTop: 10 },
  asCostTotalLabel: { fontSize: 13, color: C.slate800, fontWeight: W.extrabold },
  asCostTotalValue: { fontSize: 15, color: C.slate800, fontWeight: W.black },

  // Ventana del informe completo
  asReportHero: { backgroundColor: C.slate900, borderRadius: 16, padding: 16, gap: 3 },
  asReportHeroTitle: { color: C.white, fontSize: 17, fontWeight: W.extrabold },
  asReportHeroSub: { color: C.slate400, fontSize: 11, fontWeight: W.medium },
  asReportBanner: { marginTop: 10, borderRadius: 8, paddingVertical: 9, paddingHorizontal: 12 },
  asReportBannerText: {
    color: C.white,
    fontSize: 12,
    fontWeight: W.extrabold,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    textAlign: 'center',
  },
  asReportResumen: { color: C.slate300, fontSize: 12, fontWeight: W.medium, lineHeight: 18, marginTop: 8 },
  asReportRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.slate100,
  },
  asReportRowLabel: { fontSize: 12, color: C.slate600, fontWeight: W.semibold, flexShrink: 1 },
  asReportRowRight: { flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1, justifyContent: 'flex-end' },
  asReportRowValue: { fontSize: 12, fontWeight: W.bold, textAlign: 'right', flexShrink: 1 },

  asEventCard: {
    borderLeftWidth: 3,
    borderLeftColor: C.slate300,
    backgroundColor: C.slate50,
    borderRadius: 8,
    padding: 12,
    gap: 2,
  },
  asEventTitle: { fontSize: 13, fontWeight: W.extrabold, color: C.slate800, flex: 1 },
  asEventMeta: { fontSize: 11, color: C.slate500, fontWeight: W.medium, lineHeight: 16 },
  asEventTag: { fontSize: 10, fontWeight: W.extrabold, color: C.slate500, letterSpacing: 0.5 },

  asKmFecha: { fontSize: 11, fontWeight: W.bold, color: C.slate500 },
  asKmValue: { fontSize: 13, fontWeight: W.extrabold, color: C.slate800 },
  asKmTrack: { height: 6, backgroundColor: C.slate100, borderRadius: 9999, marginVertical: 5, overflow: 'hidden' },
  asKmFill: { height: 6, borderRadius: 9999 },
  asKmActual: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: C.slate200,
    paddingTop: 10,
  },

  asDisclaimer: { fontSize: 10, color: C.slate400, fontWeight: W.medium, textAlign: 'center', lineHeight: 15 },

  /* KPIs */
  kpiRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  kpiCard: {
    flex: 1,
    minWidth: 130,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.slate200,
  },
  kpiLabel: { fontSize: 10, fontWeight: W.semibold, color: C.slate500 },
  kpiValue: { fontSize: 17, fontWeight: W.bold, color: C.graphite, marginTop: 8, letterSpacing: -0.3 },
  kpiInsight: { fontSize: 10, fontWeight: W.medium, lineHeight: 14, marginTop: 6 },

  /* Gráficos */
  chartCard: { backgroundColor: C.white, padding: 16, borderRadius: 8, borderWidth: 1, borderColor: C.slate200, gap: 16 },
  chartTitle: { fontSize: 14, fontWeight: W.semibold, color: C.graphite },
  chartFoot: { fontSize: 11, color: C.slate400, fontWeight: W.medium, marginTop: 2 },

  barsRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 14, paddingTop: 4 },
  barCol: { flex: 1, alignItems: 'center', gap: 8 },
  barValue: { fontSize: 13, fontWeight: W.semibold, color: C.graphite },
  barTrack: {
    width: '100%',
    height: 88,
    justifyContent: 'flex-end',
    backgroundColor: C.slate50,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: C.slate100,
  },
  barFill: { width: '100%', borderTopLeftRadius: 3, borderTopRightRadius: 3, minHeight: 3 },
  barLabel: { fontSize: 10, color: C.slate500, fontWeight: W.medium },

  hbarRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  hbarLabel: { width: 86, fontSize: 11, color: C.slate600, fontWeight: W.medium },
  hbarTrack: { flex: 1, height: 6, backgroundColor: C.slate100, borderRadius: 3, overflow: 'hidden' },
  hbarFill: { height: '100%', backgroundColor: C.brand, borderRadius: 3 },
  hbarValue: { width: 18, fontSize: 12, fontWeight: W.semibold, color: C.graphite, textAlign: 'right' },

  /* Stock */
  filterBtn: {
    backgroundColor: C.slate200,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  filterBtnText: { color: C.slate700, fontWeight: W.bold, fontSize: 12 },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.slate200,
    borderRadius: 12,
    minWidth: 0,
  },
  searchInput: { flex: 1, minWidth: 0, paddingHorizontal: 10, paddingVertical: 12, fontSize: 14, fontWeight: W.medium, color: C.slate800 },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 9999,
    maxWidth: '100%',
  },
  chipActive: { backgroundColor: C.chileanNavy },
  chipInactive: { backgroundColor: C.white, borderWidth: 1, borderColor: C.slate200 },
  chipText: { fontWeight: W.bold, fontSize: 12, flexShrink: 1 },
  chipCount: { paddingHorizontal: 6, paddingVertical: 1, borderRadius: 9999, minWidth: 18, alignItems: 'center' },
  /* Pre-stock no es un estado más de la bandeja: es una bandeja de entrada.
     Por eso el chip va en ámbar y solo existe mientras haya autos esperando. */
  chipPreStock: { backgroundColor: C.amber50, borderColor: C.amber200 },
  chipPreStockActive: { backgroundColor: C.amber600, borderColor: C.amber600 },
  chipPreStockDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: C.amber600, marginRight: 6 },
  chipPreStockDotOn: { backgroundColor: C.white },
  preStockBtn: {
    marginTop: 10,
    backgroundColor: C.amber600,
    borderRadius: 12,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  preStockBtnText: { color: C.white, fontSize: 12, fontWeight: W.extrabold },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },

  emptyBox: { backgroundColor: C.white, padding: 32, borderRadius: 16, alignItems: 'center', borderWidth: 1, borderColor: C.slate200, gap: 8 },
  emptyText: { fontSize: 14, fontWeight: W.bold, color: C.slate500, textAlign: 'center' },
  resetText: { fontSize: 12, color: C.chileanTeal, fontWeight: W.bold, marginTop: 8 },

  carCard: {
    backgroundColor: C.white,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: C.slate100,
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
  },
  carThumb: { width: 88, height: 88, borderRadius: 12, overflow: 'hidden', backgroundColor: C.slate100, flexShrink: 0 },
  carThumbImg: { width: '100%', height: '100%' },
  carThumbEmpty: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center' },
  badge60: {
    position: 'absolute',
    top: 4,
    left: 4,
    backgroundColor: C.amber500,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  badge60Text: { color: C.white, fontSize: 8, fontWeight: W.extrabold },
  auctionThumbBadge: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    backgroundColor: C.chileanTeal,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  carInfo: { flex: 1, minWidth: 0, justifyContent: 'space-between' },
  carTop: { minWidth: 0 },
  carHead: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8, minWidth: 0 },
  carTitleWrap: { flex: 1, minWidth: 0 },
  carTitle: { fontWeight: W.bold, fontSize: 14, color: C.slate800 },
  carHeadActions: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, flexShrink: 0 },
  patentePill: { backgroundColor: C.slate100, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, borderWidth: 1, borderColor: C.slate200, maxWidth: 92 },
  patenteText: { fontSize: 10, fontWeight: W.bold, color: C.slate400, textTransform: 'uppercase' },
  trashSm: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: C.red50,
    borderWidth: 1,
    borderColor: C.red100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  carSpecs: { fontSize: 11, color: C.slate500, marginTop: 2, lineHeight: 15 },
  carVersion: { fontSize: 11, color: C.slate600, fontWeight: W.semibold, marginTop: 2 },
  carMargen: { fontSize: 10, color: C.emerald600, fontWeight: W.bold, marginTop: 2 },
  priceLabel: { fontSize: 10, fontWeight: W.semibold, color: C.slate400 },
  priceValue: { fontWeight: W.extrabold, fontSize: 16, color: C.slate800, letterSpacing: -0.3 },
  carCommercial: { marginTop: 8, gap: 6, minWidth: 0 },
  carPriceBlock: { minWidth: 0 },
  carBadgeRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 5, minWidth: 0 },
  estadoBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 9999, borderWidth: 1, maxWidth: '100%' },
  estadoBadgeText: { fontSize: 10, fontWeight: W.extrabold },
  stockAuctionPill: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: C.amber50, borderWidth: 1, borderColor: C.amber200, borderRadius: 9999, paddingHorizontal: 7, paddingVertical: 2 },
  stockAuctionText: { fontSize: 9, color: C.amber700, fontWeight: W.extrabold, textTransform: 'uppercase' },
  /* Tenencia: el consignado se distingue de un vistazo (Mauro, punto 11). Morado
     porque ningún estado de la tarjeta lo usa: no compite con esa semántica. */
  consignadoPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: C.purple100,
    borderRadius: 9999,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  consignadoText: { fontSize: 9, color: C.purple700, fontWeight: W.extrabold, textTransform: 'uppercase' },
  diasStock: { fontSize: 9, color: C.slate400, fontWeight: W.medium, flexShrink: 1, lineHeight: 13 },

  /* Subastas */
  segment: { flexDirection: 'row', backgroundColor: C.slate200, padding: 4, borderRadius: 12 },
  segBtn: { flex: 1, paddingVertical: 8, borderRadius: 8, alignItems: 'center' },
  segBtnActive: { backgroundColor: C.white, shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 2, elevation: 1 },
  aucCard: { backgroundColor: C.white, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: C.slate100, gap: 12 },
  publishAuctionBtn: { backgroundColor: C.chileanTeal, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 6, flexShrink: 0 },
  publishAuctionText: { color: C.white, fontWeight: W.bold, fontSize: 12 },
  auctionTopRow: { flexDirection: 'row', alignItems: 'flex-start', flexWrap: 'wrap', gap: 10, minWidth: 0 },
  auctionLead: { flexGrow: 1, flexShrink: 1, flexBasis: 190, minWidth: 0, flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
  auctionThumb: { width: 74, height: 74, borderRadius: 12, backgroundColor: C.slate100 },
  aucBadgeRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 6 },
  origenPill: { alignSelf: 'flex-start', backgroundColor: C.slate100, paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  origenText: { fontSize: 10, color: C.slate600, fontWeight: W.bold, textTransform: 'uppercase' },
  auctionStatusPill: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  auctionStatusText: { fontSize: 10, fontWeight: W.extrabold, textTransform: 'uppercase' },
  auctionTitleTap: { flexDirection: 'row', alignItems: 'center', gap: 5, alignSelf: 'flex-start', maxWidth: '100%' },
  aucTitle: { fontWeight: W.extrabold, fontSize: 16, color: C.slate800, marginTop: 4, flexShrink: 1 },
  aucSub: { fontSize: 12, color: C.slate500, flexShrink: 1 },
  aucStockLink: { fontSize: 11, color: C.chileanTeal, fontWeight: W.bold, marginTop: 2 },
  auctionFeatureHint: { flexDirection: 'row', alignItems: 'center', gap: 4, alignSelf: 'flex-start', marginTop: 6 },
  auctionFeatureHintText: { color: C.chileanTeal, fontSize: 11, fontWeight: W.extrabold },
  aucId: { fontSize: 12, fontWeight: W.bold, color: C.slate400 },
  auctionSideMeta: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'flex-end', gap: 6, flexShrink: 1 },
  timePill: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: C.amber50, borderWidth: 1, borderColor: C.amber200, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 9999 },
  timePillDone: { backgroundColor: C.slate100, borderColor: C.slate200 },
  timePillText: { fontSize: 10, fontWeight: W.extrabold, color: C.amber700 },
  auctionNoteBox: { backgroundColor: C.slate50, borderWidth: 1, borderColor: C.slate100, borderRadius: 12, padding: 10, gap: 3 },
  auctionNoteLabel: { fontSize: 9, color: C.slate400, fontWeight: W.bold, textTransform: 'uppercase' },
  auctionNoteText: { fontSize: 12, color: C.slate700, fontWeight: W.medium, lineHeight: 16 },
  aucSpecs: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, backgroundColor: C.slate50, padding: 10, borderRadius: 12 },
  aucSpecLabel: { color: C.slate400, fontSize: 10, textTransform: 'uppercase', fontWeight: W.bold },
  aucSpecValue: { fontWeight: W.semibold, color: C.slate700, fontSize: 12, flexShrink: 1 },
  aucFooterRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10, paddingTop: 8, borderTopWidth: 1, borderTopColor: C.slate100 },
  aucFooterActions: { alignItems: 'flex-start', gap: 8, maxWidth: '100%' },
  auctionProgressTrack: { height: 5, borderRadius: 9999, backgroundColor: C.slate100, overflow: 'hidden' },
  auctionProgressFill: { height: '100%', borderRadius: 9999, backgroundColor: C.chileanTeal },
  aucMoneyLabel: { fontSize: 9, textTransform: 'uppercase', fontWeight: W.bold, color: C.slate400 },
  aucMoney: { fontSize: 14, fontWeight: W.extrabold, color: C.slate700 },
  ofertarBtn: { backgroundColor: C.chileanTeal, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12 },
  ofertarBtnText: { color: C.white, fontWeight: W.extrabold, fontSize: 12 },
  pendingPill: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: C.amber50, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4 },
  pendingText: { fontSize: 12, fontWeight: W.bold, color: C.amber600 },
  viewStockBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: C.teal50, borderWidth: 1, borderColor: C.teal100, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 9999 },
  viewStockText: { fontSize: 11, color: C.chileanTeal, fontWeight: W.extrabold },
  cancelAuctionBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: C.red50, borderWidth: 1, borderColor: C.red100, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 9999 },
  cancelAuctionText: { fontSize: 11, color: C.red700, fontWeight: W.extrabold },
  addStockBtn: { backgroundColor: C.teal600, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 6 },
  addStockText: { color: C.white, fontWeight: W.extrabold, fontSize: 12 },

  /* Clientes */
  newClientBtn: { backgroundColor: C.chileanTeal, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 6, flexShrink: 0 },
  newClientText: { color: C.white, fontWeight: W.bold, fontSize: 12 },
  metricRow: { flexDirection: 'row', gap: 8, backgroundColor: C.slate100, padding: 8, borderRadius: 12 },
  metricCell: { flex: 1, backgroundColor: C.white, paddingVertical: 8, borderRadius: 8, alignItems: 'center' },
  metricLabel: { fontSize: 10, color: C.slate400, fontWeight: W.bold, textTransform: 'uppercase' },
  metricValue: { fontSize: 14, fontWeight: W.extrabold, color: C.slate800 },
  cliCard: { backgroundColor: C.white, padding: 16, borderRadius: 16, borderWidth: 1, borderColor: C.slate100, gap: 14, minWidth: 0 },
  cliCardHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 10, minWidth: 0 },
  cliTitleBlock: { flexGrow: 1, flexShrink: 1, flexBasis: 150, minWidth: 0, gap: 6 },
  cliNombre: { fontWeight: W.extrabold, fontSize: 16, color: C.slate800, lineHeight: 20 },
  cliBadgeRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  cliEstadoBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 9999 },
  cliEstadoText: { fontSize: 10, fontWeight: W.extrabold, textTransform: 'uppercase', letterSpacing: 0.3 },
  cliIconBtn: { width: 34, height: 34, borderRadius: 10, backgroundColor: C.slate50, borderWidth: 1, borderColor: C.slate200, alignItems: 'center', justifyContent: 'center' },
  cliEstadoField: { gap: 4, marginTop: 10 },
  cliGrid: { flexDirection: 'row', flexWrap: 'wrap', borderWidth: 1, borderColor: C.slate100, borderRadius: 12, overflow: 'hidden' },
  cliGridCell: { flexGrow: 1, flexShrink: 1, flexBasis: 124, minWidth: 0, padding: 12, gap: 4 },
  cliGridCellRight: { borderLeftWidth: 1, borderLeftColor: C.slate100 },
  cliGridLabel: { fontSize: 10, color: C.slate400, fontWeight: W.bold, textTransform: 'uppercase', letterSpacing: 0.3 },
  cliGridLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, minWidth: 0 },
  cliGridValue: { fontSize: 13, fontWeight: W.bold, color: C.slate800, lineHeight: 17 },
  cliVerLink: { color: C.chileanTeal, fontWeight: W.bold, fontSize: 11 },
  cliStatusBlock: { gap: 6 },
  cliNotesInput: { minHeight: 86, paddingTop: 10, textAlignVertical: 'top', backgroundColor: C.slate50 },
  cliActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  cliCallBtn: { flex: 1, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderRadius: 12, backgroundColor: C.slate50, borderWidth: 1, borderColor: C.slate200 },
  cliCallText: { fontWeight: W.bold, fontSize: 13, color: C.slate700 },
  cliWspBtn: { flex: 1, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderRadius: 12, backgroundColor: C.slate800 },
  cliWspText: { fontWeight: W.bold, fontSize: 13, color: C.white },
  cliEmpty: { alignItems: 'center', justifyContent: 'center', paddingVertical: 32, gap: 10 },
  cliEmptyText: { fontSize: 13, color: C.slate400, fontWeight: W.medium, textAlign: 'center' },

  /* Overlays (wizard / detalle) */
  overlayHeader: {
    backgroundColor: C.chileanNavy,
    paddingHorizontal: 16,
    paddingBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: C.slate800,
  },
  cancelText: { color: C.slate400, fontWeight: W.semibold, fontSize: 12 },
  overlayTitle: { color: C.white, fontWeight: W.extrabold, fontSize: 14, flex: 1, minWidth: 0, textAlign: 'center' },
  stepPill: { backgroundColor: C.slate800, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 4, borderWidth: 1, borderColor: C.slate700 },
  stepPillText: { fontSize: 12, fontWeight: W.bold, color: C.teal400, textTransform: 'uppercase', letterSpacing: 0.5 },
  progressTrack: { width: '100%', height: 6, backgroundColor: C.slate200 },
  progressFill: { height: '100%', backgroundColor: C.chileanTeal },

  stepTitle: { fontSize: 18, fontWeight: W.bold, color: C.slate800 },
  stepSub: { fontSize: 12, color: C.slate500, marginTop: 2 },

  /* Wizard cámara */
  cameraBox: {
    backgroundColor: C.slate800,
    borderRadius: 16,
    minHeight: 224,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderWidth: 2,
    borderColor: C.slate600,
    borderStyle: 'dashed',
    gap: 8,
  },
  cameraTitle: { fontSize: 14, fontWeight: W.bold, color: C.white },
  cameraSub: { fontSize: 12, color: C.slate400, textAlign: 'center' },
  captureBtn: { backgroundColor: C.chileanTeal, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 6 },
  captureText: { color: C.white, fontSize: 12, fontWeight: W.bold },
  galleryBtn: { backgroundColor: C.slate700, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 6 },
  galleryText: { color: C.slate200, fontSize: 12, fontWeight: W.bold },
  cameraActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 16 },
  cameraActionBtn: { flexGrow: 1, flexShrink: 1, minWidth: 118, justifyContent: 'center' },
  cameraAiHint: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 12 },
  cameraAiHintText: { fontSize: 11, fontWeight: W.bold, color: C.teal300 },
  previewGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  previewCell: { width: '31%', aspectRatio: 1, backgroundColor: C.slate100, borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: C.slate200 },
  previewImg: { width: '100%', height: '100%' },
  previewBadge: { position: 'absolute', bottom: 4, right: 4, backgroundColor: C.teal600, paddingHorizontal: 6, paddingVertical: 1, borderRadius: 4 },
  previewBadgeText: { color: C.white, fontSize: 8, fontWeight: W.black, textTransform: 'uppercase' },
  previewRemove: { position: 'absolute', top: 4, left: 4, backgroundColor: 'rgba(2,6,23,0.7)', width: 20, height: 20, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },

  /* Consulta de patente en el paso 1: la alternativa a llenar la ficha a mano */
  patenteBox: { backgroundColor: C.white, borderRadius: 16, borderWidth: 1, borderColor: C.slate200, padding: 14, gap: 10 },
  patenteBoxHead: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  patenteBoxTitle: { flex: 1, fontSize: 13, fontWeight: W.extrabold, color: C.slate700 },
  patenteBoxSub: { fontSize: 11, color: C.slate500, fontWeight: W.medium, lineHeight: 16 },
  patenteBuscarBtn: { backgroundColor: C.chileanTeal, borderRadius: 12, paddingVertical: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  patenteBuscarBtnOff: { backgroundColor: C.slate200 },
  patenteBuscarText: { color: C.white, fontSize: 13, fontWeight: W.extrabold },
  patenteBuscarTextOff: { color: C.slate400 },
  fichaBox: { backgroundColor: C.teal50, borderRadius: 16, borderWidth: 1, borderColor: C.teal200, padding: 14, gap: 12 },
  fichaHead: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  fichaLabel: { flex: 1, fontSize: 11, fontWeight: W.extrabold, color: C.teal700, textTransform: 'uppercase', letterSpacing: 0.5 },
  fichaPatenteTag: { backgroundColor: C.white, borderWidth: 1, borderColor: C.teal200, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  fichaPatenteTagText: { fontSize: 11, fontWeight: W.black, color: C.slate700, letterSpacing: 1.5 },
  fichaTitulo: { fontSize: 18, fontWeight: W.extrabold, color: C.slate800 },
  fichaSubtitulo: { fontSize: 12, fontWeight: W.medium, color: C.slate500, marginTop: 2 },
  fichaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  fichaCell: { flexGrow: 1, flexShrink: 1, flexBasis: 92, minWidth: 0, backgroundColor: C.white, borderRadius: 10, borderWidth: 1, borderColor: C.teal100, paddingVertical: 8, paddingHorizontal: 10 },
  fichaCellLabel: { fontSize: 9, fontWeight: W.black, color: C.slate400, textTransform: 'uppercase', letterSpacing: 0.6 },
  fichaCellValue: { fontSize: 12, fontWeight: W.bold, color: C.slate800, marginTop: 2 },
  fichaAcciones: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  fichaTomarBtn: { flexGrow: 1, flexShrink: 1, minWidth: 150, backgroundColor: C.chileanTeal, borderRadius: 12, paddingVertical: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  fichaTomarText: { color: C.white, fontSize: 13, fontWeight: W.extrabold },
  fichaOtraBtn: { flexGrow: 0, flexShrink: 1, minWidth: 104, backgroundColor: C.white, borderWidth: 1, borderColor: C.slate200, borderRadius: 12, paddingVertical: 13, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center' },
  fichaOtraText: { color: C.slate600, fontSize: 12, fontWeight: W.bold },
  fichaBuscando: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.slate50, borderRadius: 16, borderWidth: 1, borderColor: C.slate200, padding: 14 },
  fichaBuscandoText: { flex: 1, fontSize: 12, fontWeight: W.bold, color: C.slate600 },
  fichaVaciaBox: { backgroundColor: C.amber50, borderRadius: 16, borderWidth: 1, borderColor: C.amber200, padding: 14, gap: 10 },
  fichaVaciaTitulo: { flex: 1, fontSize: 13, fontWeight: W.extrabold, color: C.amber700 },
  fichaVaciaSub: { fontSize: 11, fontWeight: W.medium, color: C.slate600, lineHeight: 16 },
  fichaManualBtn: { backgroundColor: C.white, borderWidth: 1, borderColor: C.amber200, borderRadius: 12, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  fichaManualText: { color: C.amber700, fontSize: 12, fontWeight: W.extrabold },
  lecturaBox: { backgroundColor: C.white, borderRadius: 16, borderWidth: 1, borderColor: C.teal200, padding: 14, gap: 12 },
  lecturaRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  lecturaThumb: { width: 54, height: 54, borderRadius: 10, backgroundColor: C.slate100, borderWidth: 1, borderColor: C.slate200 },
  lecturaPregunta: { fontSize: 11, fontWeight: W.bold, color: C.slate500 },
  lecturaPatenteLeida: { fontSize: 24, fontWeight: W.black, color: C.slate800, letterSpacing: 3, marginTop: 2 },

  /* Campos */
  fieldLabel: { fontSize: 12, fontWeight: W.bold, color: C.slate500, textTransform: 'uppercase', marginBottom: 4 },
  fieldPair: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  fieldPairItem: { flexGrow: 1, flexShrink: 1, flexBasis: 130, minWidth: 0 },
  textInput: { borderWidth: 1, borderColor: C.slate200, borderRadius: 12, padding: 12, fontWeight: W.medium, color: C.slate800, fontSize: 14, backgroundColor: C.white },
  textArea: { minHeight: 96, borderWidth: 1, borderColor: C.slate200, borderRadius: 12, padding: 12, fontWeight: W.medium, color: C.slate800, fontSize: 14, backgroundColor: C.white, lineHeight: 20 },
  patenteInput: { borderWidth: 1, borderColor: C.slate200, borderRadius: 12, padding: 12, fontWeight: W.bold, color: C.slate800, textAlign: 'center', letterSpacing: 4, fontSize: 18, backgroundColor: C.white },
  moneyInput: { borderWidth: 1, borderColor: C.slate200, borderRadius: 12, padding: 12, fontWeight: W.bold, color: C.slate800, fontSize: 18, backgroundColor: C.white },
  dateField: { minHeight: 48, borderWidth: 1, borderColor: C.slate200, borderRadius: 12, backgroundColor: C.white, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
  dateFieldText: { flex: 1, fontSize: 14, fontWeight: W.bold, color: C.slate800 },
  calendarBackdrop: { flex: 1, backgroundColor: 'rgba(15,23,42,0.55)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  calendarCard: { width: '100%', maxWidth: 340, alignSelf: 'center', backgroundColor: C.white, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: C.slate200, shadowColor: '#000', shadowOpacity: 0.22, shadowRadius: 18, shadowOffset: { width: 0, height: 12 }, elevation: 12 },
  calendarHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  calendarNavBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: C.slate100, alignItems: 'center', justifyContent: 'center' },
  calendarTitle: { fontSize: 16, fontWeight: W.extrabold, color: C.slate800 },
  calendarWeekRow: { width: '100%', maxWidth: 280, alignSelf: 'center', flexDirection: 'row', marginBottom: 8 },
  calendarWeekText: { width: `${100 / 7}%`, textAlign: 'center', color: C.slate400, fontSize: 11, fontWeight: W.extrabold },
  calendarGrid: { width: '100%', maxWidth: 280, alignSelf: 'center', flexDirection: 'row', flexWrap: 'wrap' },
  calendarDay: { width: `${100 / 7}%`, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 20 },
  calendarDaySelected: { backgroundColor: C.chileanTeal },
  calendarDayText: { fontSize: 13, fontWeight: W.bold, color: C.slate700 },
  calendarDayTextSelected: { color: C.white },
  calendarFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginTop: 14, borderTopWidth: 1, borderTopColor: C.slate100, paddingTop: 12 },
  calendarTodayBtn: { flex: 1, paddingVertical: 11, borderRadius: 12, backgroundColor: C.teal50, alignItems: 'center' },
  calendarTodayText: { fontSize: 12, fontWeight: W.extrabold, color: C.teal700 },
  calendarClearBtn: { flex: 1, paddingVertical: 11, borderRadius: 12, backgroundColor: C.slate100, alignItems: 'center' },
  calendarClearText: { fontSize: 12, fontWeight: W.extrabold, color: C.slate600 },
  calendarDoneBtn: { flex: 1, paddingVertical: 11, borderRadius: 12, backgroundColor: C.chileanNavy, alignItems: 'center' },
  calendarDoneText: { fontSize: 12, fontWeight: W.extrabold, color: C.white },
  inlinePanel: { backgroundColor: C.white, borderRadius: 16, borderWidth: 1, borderColor: C.slate200, padding: 14 },
  inlinePanelTitle: { fontSize: 13, fontWeight: W.extrabold, color: C.slate700 },
  inlinePanelHint: { fontSize: 11, color: C.slate500, fontWeight: W.medium, marginTop: 3, lineHeight: 16 },
  inlinePanelCount: { minWidth: 24, textAlign: 'center', backgroundColor: C.teal50, color: C.teal700, borderRadius: 9999, overflow: 'hidden', fontSize: 12, fontWeight: W.extrabold, paddingVertical: 2 },
  optionWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  toggleChip: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 9999, borderWidth: 1, borderColor: C.slate200, backgroundColor: C.slate50 },
  toggleChipActive: { backgroundColor: C.chileanTeal, borderColor: C.chileanTeal },
  toggleChipText: { fontSize: 11, fontWeight: W.bold, color: C.slate600 },
  addDocBtn: { backgroundColor: C.chileanTeal, borderRadius: 12, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  addDocText: { color: C.white, fontSize: 12, fontWeight: W.extrabold },
  docRow: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.slate50, borderWidth: 1, borderColor: C.slate100, borderRadius: 12, padding: 12 },
  docTitle: { fontSize: 12, fontWeight: W.extrabold, color: C.slate700 },
  docMeta: { fontSize: 10, fontWeight: W.medium, color: C.slate400, marginTop: 2 },
  docRemove: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: C.red50, borderWidth: 1, borderColor: C.red100 },
  docsEmpty: { marginTop: 12, borderWidth: 1, borderStyle: 'dashed', borderColor: C.slate200, borderRadius: 12, padding: 18, alignItems: 'center', gap: 6 },
  docsEmptyText: { fontSize: 12, fontWeight: W.bold, color: C.slate400, textAlign: 'center' },
  margenBox: { backgroundColor: C.emerald50, borderWidth: 1, borderColor: C.emerald100, borderRadius: 16, padding: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 10 },
  margenLabel: { fontSize: 10, color: C.emerald600, fontWeight: W.bold, textTransform: 'uppercase' },
  margenValue: { fontSize: 18, fontWeight: W.black, color: C.emerald800 },
  margenTag: { backgroundColor: C.emerald200, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 9999 },
  margenTagText: { fontSize: 12, color: C.emerald800, fontWeight: W.extrabold },

  reviewCard: { backgroundColor: C.white, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: C.slate200, gap: 12 },
  reviewTitle: { fontWeight: W.extrabold, fontSize: 16, color: C.slate800, flex: 1 },
  reviewPatente: { backgroundColor: C.slate100, paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  reviewPatenteText: { color: C.slate700, fontWeight: W.extrabold, fontSize: 12, textTransform: 'uppercase' },
  hr: { height: 1, backgroundColor: C.slate100 },
  reviewGrid: { flexDirection: 'row', flexWrap: 'wrap', rowGap: 8 },
  reviewCell: { width: '50%', fontSize: 12, fontWeight: W.bold, color: C.slate700 },
  reviewCellLabel: { color: C.slate400, fontWeight: W.semibold },
  reviewMoneyLabel: { fontSize: 10, color: C.slate400, fontWeight: W.bold },
  reviewCosto: { fontWeight: W.bold, fontSize: 14, color: C.slate700 },
  reviewPrecio: { fontWeight: W.extrabold, fontSize: 18, color: C.teal600 },
  reviewCommercialGrid: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
  reviewContactText: { marginTop: 3, fontSize: 12, color: C.slate700, fontWeight: W.bold, lineHeight: 16 },

  /* Wizard footer */
  wizardFooter: { backgroundColor: C.white, borderTopWidth: 1, borderTopColor: C.slate200, padding: 16, flexDirection: 'row', gap: 12 },
  wizardBack: { flex: 1, paddingVertical: 12, backgroundColor: C.slate100, borderRadius: 12, alignItems: 'center' },
  wizardBackText: { color: C.slate700, fontWeight: W.bold, fontSize: 14 },
  wizardNext: { flex: 1, paddingVertical: 12, backgroundColor: C.chileanTeal, borderRadius: 12, alignItems: 'center' },
  wizardNextText: { color: C.white, fontWeight: W.bold, fontSize: 14 },

  /* Ficha detalle */
  gallery: { width: '100%', height: 224, backgroundColor: C.slate200 },
  galleryEmpty: { alignItems: 'center', justifyContent: 'center', gap: 8 },
  galleryEmptyText: { fontSize: 12, fontWeight: W.semibold, color: C.slate400 },
  galleryCount: { position: 'absolute', bottom: 12, right: 12, backgroundColor: 'rgba(2,6,23,0.7)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  galleryCountText: { color: C.white, fontSize: 12, fontWeight: W.bold },
  galleryDots: { position: 'absolute', bottom: 14, alignSelf: 'center', flexDirection: 'row', gap: 5 },
  galleryDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.5)' },
  galleryDotActive: { backgroundColor: C.white, width: 14 },
  detailTitle: { fontSize: 20, fontWeight: W.extrabold, color: C.slate800 },
  detailSub: { fontSize: 14, color: C.slate500, fontWeight: W.medium },
  detailEstado: { backgroundColor: C.teal50, borderWidth: 1, borderColor: C.teal200, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 9999 },
  detailAuctionBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: C.amber50, borderWidth: 1, borderColor: C.amber200, paddingHorizontal: 9, paddingVertical: 4, borderRadius: 9999 },
  detailAuctionText: { color: C.amber700, fontSize: 10, fontWeight: W.extrabold, textTransform: 'uppercase' },
  detailMargenCard: { backgroundColor: C.white, padding: 16, borderRadius: 16, borderWidth: 1, borderColor: C.slate100, gap: 8 },
  detailMiniLabel: { fontSize: 10, color: C.slate400, fontWeight: W.bold, textTransform: 'uppercase' },
  detailMiniValue: { fontSize: 12, fontWeight: W.bold, color: C.slate600 },
  detailPrecio: { fontSize: 18, fontWeight: W.black, color: C.slate800 },
  detailMargen: { fontSize: 16, fontWeight: W.extrabold, color: C.emerald600 },
  detailFinanceGrid: { flexDirection: 'row', flexWrap: 'wrap', rowGap: 10, columnGap: 12, borderTopWidth: 1, borderTopColor: C.slate100, paddingTop: 10, marginTop: 2 },
  detailTechCard: { backgroundColor: C.white, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: C.slate100 },
  detailTechTitle: { fontWeight: W.bold, fontSize: 12, color: C.slate400, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 12 },
  /* Sección colapsable de la ficha (punto 23): cerrada muestra el título con un
     resumen de una línea; abierta, el contenido completo. */
  seccionHead: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  seccionTitulo: { fontWeight: W.bold, fontSize: 12, color: C.slate400, textTransform: 'uppercase', letterSpacing: 0.5 },
  seccionResumen: { fontSize: 12, color: C.slate600, fontWeight: W.semibold, marginTop: 4, flexShrink: 1 },
  /* Modo cliente (punto 24): el mayorista muestra el auto desde su propio
     teléfono. Es un ojo en la cabecera, no una tarjeta: encendido tapa costo,
     margen y toda la gestión, y deja la ficha en lo que le importa al cliente. */
  ojoModoCliente: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.slate100,
    borderWidth: 1,
    borderColor: C.slate200,
  },
  ojoModoClienteOn: { backgroundColor: C.chileanNavy, borderColor: C.chileanNavy },
  detailTechGrid: { flexDirection: 'row', flexWrap: 'wrap', rowGap: 12, columnGap: 12 },
  detailHeaderRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10, minWidth: 0 },
  detailHeaderText: { flexGrow: 1, flexShrink: 1, flexBasis: 180, minWidth: 0 },
  detailHeaderBadges: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start', flexWrap: 'wrap', gap: 6, maxWidth: '100%' },
  detailMoneyRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10, minWidth: 0 },
  techItem: { flexGrow: 1, flexShrink: 1, flexBasis: '46%', minWidth: 108 },
  techLabel: { color: C.slate400, fontWeight: W.bold, fontSize: 12 },
  techValue: { fontWeight: W.semibold, color: C.slate800, fontSize: 12, lineHeight: 16 },
  vehicleContactCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: C.slate50, borderWidth: 1, borderColor: C.slate100, borderRadius: 12, padding: 12, minWidth: 0 },
  vehicleContactLabel: { fontSize: 10, color: C.slate400, fontWeight: W.bold, textTransform: 'uppercase', marginBottom: 4 },
  vehicleContactName: { fontSize: 13, color: C.slate800, fontWeight: W.extrabold },
  vehicleContactPhone: { fontSize: 12, color: C.slate500, fontWeight: W.medium, marginTop: 2 },
  vehicleContactActions: { flexDirection: 'row', gap: 8, flexShrink: 0 },
  vehicleContactBtn: { width: 34, height: 34, borderRadius: 10, backgroundColor: C.white, borderWidth: 1, borderColor: C.slate200, alignItems: 'center', justifyContent: 'center' },
  equipmentList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  equipmentPill: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: C.teal50, borderWidth: 1, borderColor: C.teal100, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 9999 },
  equipmentText: { color: C.teal700, fontSize: 11, fontWeight: W.bold },
  emptySectionText: { color: C.slate400, fontSize: 12, fontWeight: W.medium },
  detailNoteInset: { marginTop: 12, backgroundColor: C.slate50, borderRadius: 12, padding: 12, borderWidth: 1, borderColor: C.slate100 },
  detailNoteInsetLabel: { fontSize: 10, color: C.slate400, fontWeight: W.bold, textTransform: 'uppercase', marginBottom: 4 },
  detailNoteInsetText: { color: C.slate600, fontSize: 12, fontWeight: W.medium, lineHeight: 18 },
  /* Vistas del sitio web en la ficha (ronda 3, punto 8). David pidió "un número
     nomás"; la tendencia de los últimos días es apuesta nuestra, para ver si le
     sirve al compraventero. */
  vistasNumero: { fontSize: 26, fontWeight: W.black, color: C.slate900 },
  vistasSub: { fontSize: 12, color: C.slate500, marginTop: 2 },
  vistasBarras: { flexDirection: 'row', alignItems: 'flex-end', gap: 3, height: 48, marginTop: 14 },
  vistasBarra: { flex: 1, minWidth: 2, borderRadius: 2, backgroundColor: C.teal300 },
  vistasBarraHoy: { backgroundColor: C.chileanTeal },
  vistasEje: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
  vistasEjeText: { fontSize: 10, color: C.slate400 },

  /* Motor de Precios con la cara de Autored (ronda 3, punto 6). Las tres tarjetas de
     precio son david-pantallas-4.png; el de venta va destacado en oscuro como en la
     captura, porque es el que ellos ponen al centro. */
  mpPrecioCard: {
    flex: 1,
    minWidth: 0,
    backgroundColor: C.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.slate200,
    padding: 14,
    gap: 8,
    alignItems: 'center',
  },
  mpPrecioCardFuerte: { backgroundColor: C.chileanNavy, borderColor: C.chileanNavy },
  mpPrecioLabel: {
    fontSize: 10,
    fontWeight: W.black,
    color: C.slate500,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    textAlign: 'center',
  },
  mpPrecioLabelFuerte: { color: C.teal200 },
  mpPrecioValor: { fontSize: 19, fontWeight: W.black, color: C.slate900, textAlign: 'center' },
  mpPrecioValorFuerte: { color: C.white },
  mpRangoLabel: { fontSize: 9, fontWeight: W.bold, color: C.slate400, letterSpacing: 0.5 },
  mpRangoRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap', justifyContent: 'center' },
  mpRangoPill: {
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: C.slate200,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  mpRangoPillFuerte: { borderColor: C.slate700, backgroundColor: C.slate800 },
  mpRangoText: { fontSize: 10, fontWeight: W.bold, color: C.slate600 },
  mpRangoTextFuerte: { color: C.white },
  mpEstrellas: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  mpComercialidadText: { fontSize: 12, fontWeight: W.bold, color: C.slate600 },
  mpResumenRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: C.slate100,
    gap: 12,
  },
  mpResumenLabel: { fontSize: 12, color: C.slate500 },
  mpResumenValor: { fontSize: 12, fontWeight: W.bold, color: C.slate800, flexShrink: 1, textAlign: 'right' },
  mpPubRow: {
    backgroundColor: C.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.slate200,
    padding: 12,
    gap: 4,
  },
  mpPubTitulo: { fontSize: 12, fontWeight: W.bold, color: C.slate800 },
  mpPubMeta: { fontSize: 11, color: C.slate400 },
  mpPubPrecio: { fontSize: 14, fontWeight: W.black, color: C.slate900 },

  /* Sección de Informes (ronda 3, punto 4). La captura de Autored es una tabla de
     escritorio con siete columnas; en móvil cada informe es una tarjeta, que es el
     patrón que la bandeja de Stock ya usa. */
  informeTipoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.slate200,
    backgroundColor: C.white,
  },
  informeTipoRowOn: { borderColor: C.chileanTeal, backgroundColor: C.teal50 },
  informeRadio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: C.slate300,
    alignItems: 'center',
    justifyContent: 'center',
  },
  informeRadioOn: { borderColor: C.chileanTeal },
  informeRadioDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: C.chileanTeal },
  informeTipoTitulo: { fontSize: 13, fontWeight: W.extrabold, color: C.slate800 },
  informeTipoSub: { fontSize: 11, color: C.slate500, marginTop: 2 },
  informeCard: {
    backgroundColor: C.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.slate200,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  informeCardPatente: { fontSize: 17, fontWeight: W.black, color: C.slate900, letterSpacing: 1 },
  informeCardAuto: { fontSize: 12, color: C.slate500, marginTop: 1 },
  informeCardMeta: { fontSize: 11, color: C.slate400, marginTop: 6 },
  informeTipoPill: {
    alignSelf: 'flex-start',
    backgroundColor: C.slate100,
    borderRadius: 9999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 6,
  },
  informeTipoPillText: { fontSize: 10, fontWeight: W.bold, color: C.slate600 },
  informeEstadoPill: {
    backgroundColor: C.teal50,
    borderRadius: 9999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  informeEstadoText: { fontSize: 10, fontWeight: W.black, color: C.teal700, letterSpacing: 0.4 },

  /* Módulo de Transferencias (ronda 3, punto 5). La captura de Autored es una tabla
     de ocho columnas más tres filas de filtros; en el teléfono cada solicitud es una
     fila-tarjeta con esos mismos campos. */
  trNuevaBtn: {
    backgroundColor: C.chileanNavy,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  trNuevaBtnText: { color: C.white, fontWeight: W.extrabold, fontSize: 13 },
  trFila: {
    backgroundColor: C.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.slate200,
    padding: 14,
    gap: 10,
  },
  trFilaHead: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  trPatente: { fontSize: 17, fontWeight: W.black, color: C.slate900, letterSpacing: 1 },
  trAuto: { fontSize: 12, color: C.slate500, marginTop: 1 },
  trPie: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: C.slate100,
    paddingTop: 10,
    gap: 8,
  },
  trMeta: { fontSize: 11, color: C.slate400, flexShrink: 0 },
  trSigla: {
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexShrink: 1,
    minWidth: 0,
  },
  trSiglaText: { fontSize: 11, fontWeight: W.bold },
  trEstadoPill: { borderRadius: 9999, paddingHorizontal: 10, paddingVertical: 4 },
  trEstadoText: { fontSize: 11, fontWeight: W.bold },
  /* Las cuatro tarjetas de tipo de la pantalla de crear (david-pantallas-2.png). */
  trTipoCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    gap: 8,
  },
  trTipoIcono: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trTipoTitulo: { fontSize: 15, fontWeight: W.extrabold, color: C.slate900 },
  trTipoDesc: { fontSize: 12, color: C.slate600, lineHeight: 17 },

  /* Acceso directo a Transferencias desde la ficha del auto vendido (ronda 3,
     punto 7). Reemplaza a la tarjeta de transferencia notarial que vivía en el
     bloque de AutoSafe. */
  transferirCard: {
    backgroundColor: C.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.slate200,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  transferirIcono: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: C.chileanNavy,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transferirTitulo: { fontSize: 14, fontWeight: W.extrabold, color: C.slate900 },
  transferirSub: { fontSize: 11, color: C.slate500, marginTop: 2 },

  /* Inspección de recepción con IA. La tarjeta salió de la ficha el 1-09 (ronda 3,
     punto 3), así que estos estilos no los usa nadie hoy: se dejan para cuando el
     módulo vuelva a enchufarse. Ver src/inspection/README.md. */
  inspCtaCard: {
    backgroundColor: C.chileanNavy,
    borderRadius: 16,
    padding: 16,
  },
  inspCtaIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: C.chileanTeal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inspCtaTitle: { fontSize: 14, fontWeight: W.extrabold, color: C.white },
  inspCtaSub: { fontSize: 11, color: C.slate300, marginTop: 3, lineHeight: 15 },
  inspDoneCard: {
    backgroundColor: C.teal50,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: C.teal200,
  },
  inspDoneIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: C.teal100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inspTitle: { fontSize: 14, fontWeight: W.extrabold, color: C.slate900 },
  inspSub: { fontSize: 12, color: C.teal800, marginTop: 2, fontWeight: W.semibold },

  notasBox: { backgroundColor: C.slate100, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: C.slate200 },
  notasLabel: { fontWeight: W.bold, color: C.slate500, fontSize: 12, marginBottom: 4 },
  notasText: { color: C.slate600, fontSize: 12, fontWeight: W.medium, lineHeight: 18 },
  detailFooter: { backgroundColor: C.white, borderTopWidth: 1, borderTopColor: C.slate200, padding: 16, gap: 10 },
  detailFooterActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  detailActionGray: { flex: 1, minWidth: 0, paddingVertical: 12, paddingHorizontal: 8, backgroundColor: C.slate100, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  detailFooterAction: { flexBasis: 132 },
  detailActionGrayText: { color: C.slate700, fontWeight: W.extrabold, fontSize: 12 },
  detailEditBtn: { backgroundColor: C.chileanNavy, paddingVertical: 14, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  detailEditText: { color: C.white, fontWeight: W.extrabold, fontSize: 12 },
  detailDeleteBtn: { backgroundColor: C.red50, borderWidth: 1, borderColor: C.red100, paddingVertical: 14, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  detailDeleteText: { color: C.red700, fontWeight: W.extrabold, fontSize: 12 },

  /* Sheets */
  sheetHeader: { padding: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: C.slate100 },
  sheetTitle: { fontWeight: W.extrabold, fontSize: 14, color: C.slate800 },
  sheetTitleSm: { fontWeight: W.bold, fontSize: 14, color: C.slate800 },
  sheetFieldLabel: { fontSize: 12, fontWeight: W.bold, color: C.slate400, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 4 },
  sheetInput: { borderWidth: 1, borderColor: C.slate200, borderRadius: 12, padding: 10, fontSize: 12, fontWeight: W.semibold, color: C.slate700, backgroundColor: C.white, minWidth: 0 },
  sheetNotesInput: { minHeight: 82, paddingTop: 10, textAlignVertical: 'top' },
  filtroDiasBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: C.teal50, borderRadius: 12, borderWidth: 1, borderColor: C.teal200, paddingVertical: 8, paddingHorizontal: 12 },
  filtroDiasText: { flex: 1, fontSize: 11, fontWeight: W.semibold, color: C.teal700 },
  kpiNota: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: C.amber50, borderRadius: 12, borderWidth: 1, borderColor: C.amber200, padding: 10 },
  kpiNotaText: { flex: 1, fontSize: 10, fontWeight: W.medium, color: C.amber700, lineHeight: 14 },
  motorAltaBox: { backgroundColor: C.teal50, borderRadius: 16, borderWidth: 1, borderColor: C.teal200, padding: 14 },
  motorAltaTitle: { fontSize: 12, fontWeight: W.extrabold, color: C.teal700, textTransform: 'uppercase', letterSpacing: 0.5 },
  motorAltaPrecio: { fontSize: 26, fontWeight: W.extrabold, color: C.slate800, marginTop: 8 },
  motorAltaSub: { fontSize: 11, fontWeight: W.medium, color: C.slate500, marginTop: 2 },
  motorAltaEmpty: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.slate50, borderRadius: 16, borderWidth: 1, borderColor: C.slate200, borderStyle: 'dashed', padding: 14 },
  motorAltaEmptyText: { flex: 1, fontSize: 11, fontWeight: W.medium, color: C.slate500 },
  sheetToggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10, paddingHorizontal: 12, borderRadius: 12, backgroundColor: C.slate50, borderWidth: 1, borderColor: C.slate200 },
  sheetToggleText: { fontSize: 12, fontWeight: W.bold, color: C.slate600 },
  buscaStockLabel: { fontSize: 11, fontWeight: W.bold, color: C.slate400, marginTop: 10 },
  buscaStockChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 12,
    backgroundColor: C.slate50,
    borderWidth: 1,
    borderColor: C.slate200,
  },
  buscaStockChipOn: { backgroundColor: C.chileanTeal, borderColor: C.chileanTeal },
  buscaStockChipText: { fontSize: 12, fontWeight: W.bold, color: C.slate700 },
  buscaStockChipSub: { fontSize: 10, fontWeight: W.semibold, color: C.slate400, marginTop: 1 },
  sugerenciaChip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: C.slate100, borderWidth: 1, borderColor: C.slate200 },
  sugerenciaText: { fontSize: 11, fontWeight: W.semibold, color: C.slate600 },
  sheetRangeValue: { fontSize: 12, fontWeight: W.extrabold, color: C.chileanTeal },
  sheetFooter: { padding: 16, borderTopWidth: 1, borderTopColor: C.slate100, flexDirection: 'row', gap: 8 },
  sheetBtnGray: { flex: 1, paddingVertical: 12, backgroundColor: C.slate100, borderRadius: 12, alignItems: 'center' },
  sheetBtnGrayText: { color: C.slate600, fontWeight: W.bold, fontSize: 12 },
  sheetBtnTeal: { flex: 1, paddingVertical: 12, backgroundColor: C.chileanTeal, borderRadius: 12, alignItems: 'center' },
  sheetBtnTealText: { color: C.white, fontWeight: W.bold, fontSize: 12 },
  sheetPrimaryBtn: { paddingVertical: 14, backgroundColor: C.chileanTeal, borderRadius: 12, alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 },
  sheetPrimaryText: { color: C.white, fontWeight: W.extrabold, fontSize: 12 },
  publishStickyBtn: { paddingVertical: 13, backgroundColor: C.chileanTeal, borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 },
  noteHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginBottom: 4 },
  dismissKeyboardBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: C.teal50, borderWidth: 1, borderColor: C.teal100, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 9999 },
  dismissKeyboardText: { color: C.chileanTeal, fontSize: 11, fontWeight: W.extrabold },
  auctionNoteInput: { minHeight: 86, maxHeight: 118, borderWidth: 1, borderColor: C.slate200, borderRadius: 12, padding: 12, fontWeight: W.medium, color: C.slate800, fontSize: 14, backgroundColor: C.white, lineHeight: 20 },
  featureHeroImg: { width: '100%', height: 150, borderRadius: 14, backgroundColor: C.slate100 },
  featureQuickGrid: { flexDirection: 'row', flexWrap: 'wrap', rowGap: 10, columnGap: 16, backgroundColor: C.slate50, borderWidth: 1, borderColor: C.slate100, borderRadius: 14, padding: 12 },
  featureListCard: { backgroundColor: C.white, borderWidth: 1, borderColor: C.slate100, borderRadius: 14, padding: 14 },
  featureRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12, paddingVertical: 9, borderTopWidth: 1, borderTopColor: C.slate100 },
  featureLabel: { flex: 0.42, fontSize: 11, color: C.slate400, fontWeight: W.bold, textTransform: 'uppercase' },
  featureValue: { flex: 0.58, fontSize: 12, color: C.slate700, fontWeight: W.semibold, textAlign: 'right', lineHeight: 17 },
  featureDetailPill: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: C.teal50, borderWidth: 1, borderColor: C.teal100, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 9 },
  featureDetailLabel: { fontSize: 10, color: C.teal700, fontWeight: W.extrabold, textTransform: 'uppercase', marginBottom: 2 },
  featureDetailText: { fontSize: 12, color: C.slate700, fontWeight: W.semibold, lineHeight: 17 },

  bigValueBox: { backgroundColor: C.slate50, padding: 16, borderRadius: 16, alignItems: 'center', borderWidth: 1, borderColor: C.slate100 },
  bigValueLabel: { fontSize: 10, color: C.slate400, fontWeight: W.bold, textTransform: 'uppercase' },
  bigValue: { fontSize: 24, fontWeight: W.black, color: C.slate800 },
  sealedInfoBox: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, backgroundColor: C.teal50, borderWidth: 1, borderColor: C.teal100, borderRadius: 12, padding: 12 },
  sealedInfoText: { flex: 1, fontSize: 12, lineHeight: 16, color: C.slate700, fontWeight: W.medium },
  stepperRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  stepperBtn: { width: 56, height: 56, backgroundColor: C.slate100, borderRadius: 28, alignItems: 'center', justifyContent: 'center' },
  stepperMargen: { fontSize: 16, fontWeight: W.extrabold, color: C.emerald600 },
  bidMinText: { fontSize: 12, fontWeight: W.semibold, color: C.slate500, textAlign: 'center' },

  statusGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  statusBtn: { width: '47%', flexGrow: 1, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 12, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statusBtnActive: { backgroundColor: C.chileanNavy, borderColor: C.chileanNavy },
  statusBtnInactive: { backgroundColor: C.slate50, borderColor: C.slate200 },
});
